version: '3.1'

services:
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      environment:
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/db:/data/db
      command: mongod --smallfiles --logpath=/dev/null # --quiet

  web:
    image: java:alpine
    volumes:
      - ./target/groupservice-0.1.jar:/var/app.jar:z
    command: java -Djava.net.preferIPv4Stack=true -jar /var/app.jar -cluster
    ports:
      - 80:8082
    environment:
      MONGOSERVER: mongodb
      MONGOPORT: 27017
    depends_on:
      - mongodb

